In [84]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np
import itertools
# Plotting library
from matplotlib import pyplot
import math 
# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
from scipy.io import loadmat

# library written for this exercise providing additional functions for assignment submission, and others
import utils
from random import randrange
# tells matplotlib to embed plots within the notebook
%matplotlib inline

In [85]:
class Point:
    RRHsum=0
    def __init__(self, x,  y):
        self.x = x
        self.y = y
    
  
 
#class pos_Obj:
#    def __init__(self, RB,  Conn):
#        self.RB = RB
#        self.Conn = Conn

  


## Generating the RRH and users

In [86]:


#n= total number of users
# m = total number of RRH 


n=5
m=15
users = [Point(0,0) for i in range(n)]
for user in users:
    user.x= randrange(10)
    user.y=randrange(10)

rrhs= [Point(0,0) for i in range(m)]
for rrh in rrhs:
    rrh.x= randrange(10)
    rrh.y=randrange(10)



## Generating connection Matrix for local search

In [87]:
from itertools import product


In [88]:


round(2.2)

2

## Generating random sol for Genetics Algorithm

In [89]:
def randconn(N,M,users,rrhs, Q):
    flag=True
    """initializing the two matrices of connections and RRH sum"""
    
    x = np.zeros((N,M),dtype = int)
    RRHsum = np.zeros((N,M),dtype = int)
    for k in range(N):
        """random index to put the 1 in the users row"""
        
        index = np.random.randint(0,M-1)
        distance = math.sqrt((users[k].x - rrhs[index].x)**2 + (users[k].y - rrhs[index].y)**2)
        S = 5 - (10*math.log(25)) - (20*math.log(2350)) - (30*math.log(distance)) - (6*(distance/5)) + 28
        C = 180000*math.log((1+pow(10,(S/(-174+ (10*math.log(180000)))/10))),2)
        Rb = 2000000 / C
       
        """ updating matrix values"""
        
        RRHsum[k][index]= RRHsum[k][index]+math.ceil(Rb)
        x[k][index] = 1
        
        """ Checking whether the column sum value in RRh sum matrix is greater than Q RB.. if true the function returns flag=False
            and this function won't be used. and the method is called again to generate another valid matrix
        """
        if RRHsum.sum(axis=0)[index] >Q:
            
            flag=False
            break
        
        
        #x = np.zeros((N,M))
        
       
    
    return x,RRHsum, flag

In [133]:
def crossover(RRHsum,RRHsum2):
    #some usefull variables
    #halfrows = int(RRHsum.shape[0]/2)
    #halfcolumns =  int(RRHsum.shape[1]/2)
    cutoff = int(RRHsum.shape[0]/2)
    print(cutoff)
    #restcut = int(RRHsum.shape[1]) - cutoff
    final = np.zeros(RRHsum.shape,dtype= int)
    final2 = np.zeros(RRHsum2.shape,dtype = int)
    #cutting it for crossover
    
    firstcut1 = RRHsum[0:cutoff,:]
    print(firstcut1.shape)
    firstcut2 = RRHsum[cutoff:,:]
    print(firstcut2.shape)
    
    secondcut1 = RRHsum2[0:cutoff,:]
    print(secondcut1.shape)
    secondcut2 = RRHsum2[cutoff:,:]
    print(secondcut2.shape)
    

    final[0:cutoff,:] = secondcut1
    print(firstcut2.shape)
    print(final[0:cutoff,:].shape)
    final[cutoff:,:] = firstcut2
    
    final2[0:cutoff,:] = firstcut1
    final2[cutoff:,:] = secondcut2
    
    
    return final,final2
    
    

In [137]:
n, m = 5, 15
Q= 7
"""loop to generate the valid matrix for genetics algorithm"""

loop= False
while loop==False:
    conn,rrhSum,flag = randconn(n,m,users,rrhs, Q)
    loop=flag
    
loop= False
while loop==False:
    conn2,rrhSum2,flag2 = randconn(n,m,users,rrhs, Q)
    loop=flag
    

print(rrhSum)
print(rrhSum2)

final,final2 = crossover(rrhSum,rrhSum2)
print(final)
print(final2)
matrix1= np.array([
    [1, 2, 3, 4, 5 ],
    [6 ,7 ,8 ,9 ,10],
    [11 ,12 ,13 ,14 ,15],
    [16, 17, 18 ,19 ,20]
])

matrix2 =np.array([
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35],
    [36, 37, 38, 39, 40]
])
example,example2 = crossover(matrix1,matrix2)
print(matrix1)
print(matrix2)
print(example)
print(example2)

[[0 0 0 7 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 7 0 0 0 0]
 [0 7 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 7 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 7 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 7 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 7 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 7 0 0 0 0 0 0 0]]
2
(2, 15)
(3, 15)
(2, 15)
(3, 15)
(3, 15)
(2, 15)
[[0 0 7 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 7 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 7 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 7 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 7 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 7 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 7 0 0 0 0 0 0 0]]
2
(2, 5)
(2, 5)
(2, 5)
(2, 5)
(2, 5)
(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6 


## Genetics Algorithm using generated matrix

## Some test codes

In [ ]:
class Trial:
   
    def __init__(self, x ,  S=0):
        self.x =x
        self.S= S
    def add(self , sum_A):
        self.S = self.S +sum_A
        print(self.S )
x= Trial(2)
x.add(10)
x.add(100)

y=Trial(3)
x.add(5)
print(x.S)